### ISSUE TITLE
Question about the latent_dim parameter.

### ISSUE THREAD

**Issue by hot-dog** [EmilienDupont/coinpp#1]
The source code provide the training configuration for dataset of kodak and cifar10 and i am a little confused about the value of latent_dim parameter. It's set to 64 for kodak dataset and 384 for cifar10 dataset, i thought kodak dataset is much more complex than cifar10 dataset and it's lantent_dim should be larger than cifar10 dataset, but it's contrary, why? And could you share the empirical advice for selecting a proper latent_dim value for a certain dataset?

**Comment by EmilienDupont** [comment]
You are indeed correct that kodak is more complex than cifar10. However, the `latent_dim` for kodak corresponds to the `latent_dim` _per patch_ which means that the total number of latent dimensions when you store the image will be `num_patches * latent_dim`. Since we use `32 x 32` sized patches for kodak, we will have `384 * 64 = 25k` latents, which is indeed much larger than the 384 for cifar10.

Selecting the proper `latent_dim` for a certain dataset is mostly empirical. For kodak and cifar10 for example, we chose the `latent_dim` such that the `bpp` values would roughly line up with the typical values people use for rate distortion plots.

Hope this helps!

**Comment by hot-dog** [comment]
Thanks for your reply!
What i am confused about is that for a patch of image with size 32x32, the latents size of cifar10 image is 384, which is 6 times of kodak image. I thought that cifar10 dataset is no more complex than kodak, so the latents size should also be less than kodak's or equal at the worst.
I have trained and tested the code on my dataset(satellite imagery with single channel) with the configuration of kodaks, but the reconstruction quality is very poor, there is obvious block effect and the details can hardly be seen, my dataset contains 70k+ images of size 64x64,  the patch_shape is set to 32x32, the network is trained over 100k+ iterations with batchsize of 64.
Could you please give some advice what may be wrong or what i have missed?
By the way, this is really an interesting work, thanks for your great job.

**Comment by hot-dog** [comment]
what's more, i have also tried the lantet_dim=384 and the reconstruction quality is much better, but with a low compression ratio.

**Comment by EmilienDupont** [comment]
Thanks for your reply and the clarifications! You are right that cifar10 is 32 x 32 and the patches for kodak are 32 x 32 as well. However, the patches from kodak generally look simpler than cifar10 images. Since the patches are so small relative to the image, they often look like e.g. just a single color or a very simple pattern (like blue sky or a branch from a tree), so we can usually get good reconstructions with smaller latent dims.

Great to hear you are trying this on satellite imagery too! I imagine the reason why the reconstructions are bad with the kodak settings is that your 32 x 32 patches contain much more information than kodak 32 x 32 patches (since your original image is 64 x 64). It is therefore likely that you will need bigger latent dims.

Also, as your satellite imagery looks like a single channel image, you will likely get much better compression ratios using traditional autoencoder based methods. Indeed, as we show in the image experiments in the paper, we are still far from matching image specific codecs. COIN++ is useful is for data modalities that are very compressible but cannot be compressed with other methods, simply because applicable codecs don't exist (e.g. data on manifolds). However, if you can treat your data as an image and you want to get the best compression performance, I would recommend using autoencoder based codecs (for now 😉).

**Comment by hot-dog** [comment]
Thank you very much for your explanation and recommendation, i get it and will give autoencoder a try.
Issue closed.
